Improving the documentation.
realm/realm-js pull request #3319
Opened 2020-10-09 09:18 UTC by cesarvr

The old version links to an NDK version that is not supported by the current project configuration. 

[related to this discussion](https://github.com/realm/realm-js/pull/3315#issuecomment-706054896)

2020-10-09 09:20 UTC, kraenhansen requested changes

2020-10-09 09:20 UTC, kraenhansen commented on README.md
> +* Android NDK 21.0 (Only available on the SDK Manager on Android Studio)
```suggestion
* Android NDK 21.0 (available via the SDK Manager in Android Studio / Android SDK Tools)
```

2020-10-09 11:05 UTC, kneth approved these changes

2020-10-09 11:30 UTC, kraenhansen approved these changes

2020-10-09 11:49 UTC, steffenagger approved these changes
I think there's also a CLI approach via `cd $ANDROID_HOME/tools/bin && ./sdkmanager --install "ndk;21.0.6113669"`, but haven't had the time to test.

2020-10-09 12:09 UTC, cesarvr commented
> I think there's also a CLI approach via `cd $ANDROID_HOME/tools/bin && ./sdkmanager --install "ndk;21.0.6113669"`, but haven't had the time to test.

Nice @steffenagger, I would try that. 👍

2020-10-12 11:23 UTC, blagoev requested changes
please revert the unneeded change

2020-10-12 11:23 UTC, blagoev commented on README.md
> +#run in elevated
why this change.

2020-10-13 07:28 UTC, blagoev approved these changes

2020-10-13 11:11 UTC, merged