Wrote my take-aways from debugging a memory leak
realm/realm-js pull request #3523
Opened 2021-01-25 14:05 UTC by kraenhansen

## What, How & Why?

I hope this may help anyone trying to debug memory leaks in our repository.

I've tagged a lot of you for review, feel free to skip this though 🙂 
Read if this might be interesting for you or have prior experience with debugging memory leaks.

2021-01-25 14:40 UTC, fronck commented on contrib/guide-memory-leaks.md
> +There's a couple of reasons this guide won't dwelve too much on this type of leak:
[spelling]  *"dwell on" or "delve into"

2021-01-25 14:49 UTC, fronck requested changes
Minor grammar and typo corrections.

Otherwise:  nice :)

2021-01-25 14:49 UTC, fronck commented on contrib/guide-memory-leaks.md
> +Run the process with the `--inspect` (or `--inspect-brk` to pause the process until the debugger attach) runtime parameter:
```suggestion
Run the process with the `--inspect` (or `--inspect-brk` to pause the process until the debugger attaches) runtime parameter:
```

2021-01-25 14:49 UTC, fronck commented on contrib/guide-memory-leaks.md
> +Navigate a Chromium browser to and click the "inspect" link next to the target representing the Node.js process
Navitage a Chromium browser to where?

2021-01-25 14:49 UTC, fronck commented on contrib/guide-memory-leaks.md
> +Majority of our code is C++ code wrapping the Realm Object Store to expose object and property access. This is probably the part of our repository most ripe for memory leaks.
```suggestion
The majority of our code is C++ code wrapping the Realm Object Store to expose object and property access. This is probably the part of our repository most ripe for memory leaks.
```

2021-01-25 14:49 UTC, fronck commented on contrib/guide-memory-leaks.md
> +An advantage is that it provides a great GUI. Disadvantage is that it cannot attach to all processes (ex Android process running in a simulator) and that it's only available on macOS.
```suggestion
An advantage is that it provides a great GUI. Disadvantage is that it cannot attach to all processes (e.g., Android process running in a simulator) and that it's only available on macOS.
```

2021-01-25 14:49 UTC, fronck commented on contrib/guide-memory-leaks.md
> +gperftools can be installed using brew.
```suggestion
On MacOS, gperftools can be installed using brew.
```

2021-01-25 14:49 UTC, fronck commented on contrib/guide-memory-leaks.md
> +Some might say that Valgrind is not exactly the "new kid on the block" and as such has a UI and output which is harder to wrap your head around. Valgrind can be installed [via a brew tab](https://git
```suggestion
Some might say that Valgrind is not exactly the "new kid on the block" and as such has a UI and output which is harder to wrap your head around. Valgrind can be installed [via a brew tap](https://github.com/LouisBrunner/valgrind-macos) on macOS. 
```

2021-01-26 07:01 UTC, cesarvr approved these changes

2021-01-26 08:03 UTC, kneth approved these changes
Nice :-)

2021-01-26 11:33 UTC, fronck approved these changes
👍

2021-01-26 11:38 UTC, steffenagger approved these changes

2021-01-26 11:53 UTC, merged