Update prebuild-install and lock runtime
realm/realm-js pull request #3679
Opened 2021-04-08 10:09 UTC by takameyer

In preparation for github actions, we need to update prebuild-install to allow for
local installation of a prebuild package.  This is provided in version 6.1.1.

Also, in the binary.package_name field the `napi` runtime is hardcoded.
The runtime is now hard coded into the install script for `prebuild-install`, as we don't support any other runtimes.

This closes #3670 

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

2021-04-08 10:56 UTC, kneth requested changes
Either

1. Target `develop`
2. Revert update of `vendor/realm-core`

2021-04-08 11:17 UTC, takameyer commented
Reverted change to core version

2021-04-09 06:48 UTC, kneth approved these changes

2021-04-09 15:23 UTC, fealebenpae approved these changes

2021-04-09 15:26 UTC, merged