Validate configuration
realm/realm-js pull request #3772
Opened 2021-06-01 15:18 UTC by kneth

## What, How & Why?

This closes #3771 

## ☑️ ToDos
* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* [x] 🚦 Tests
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* ~[ ] jsdoc files updated~
* ~[ ] Chrome debug API is updated if API is available on React Native~

2021-06-02 09:40 UTC, fronck approved these changes

2021-06-02 10:43 UTC, nirinchev requested changes
Is `disableFormatUpgrade` an option compatible with sync? I would imagine that this would prevent Sync from writing to the file. Additionally, we should express these incompatibilities in the typescript definitions so that people who are using an editor that respects ts definitions will get early feedback if they try to construct an invalid config.

2021-06-08 13:52 UTC, nirinchev approved these changes

2021-06-10 07:04 UTC, takameyer requested changes
Just a formatting issue that should be addressed.

I am not completely satisfied with how the typings resolve for configuration, but I have no alternative solution at the moment.  If the developer explicitly uses `ConfigurationWithSync`, then the TS errors look nice, but if they use the `Configuration` union, the TS errors are quite vague.  If I come up with a better solution later, I will make a separate PR.

Otherwise, LGTM

2021-06-10 07:04 UTC, takameyer commented on types/index.d.ts
> +        sync?: never,
```suggestion
        sync: SyncConfiguration;
        migration?: never;
        inMemory?: never;
        deleteRealmIfMigrationNeeded?: never;
        disableFormatUpgrade?: never;
    }

    interface ConfigurationWithoutSync extends BaseConfiguration {
        sync?: never;
```
The interface properties should end in `;`

2021-06-10 08:46 UTC, takameyer approved these changes

2021-06-10 08:51 UTC, merged