Test object listner for linked object changes
realm/realm-js pull request #4316
Opened 2022-02-07 09:04 UTC by takameyer

## What, How & Why?

This closes # ???

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

2022-02-17 14:31 UTC, tomduncalf reviewed
Just realised I had not submitted this comment!

2022-05-11 07:40 UTC, kraenhansen commented
It deletes the vendor/.npmignore  … that seems unrelated and as a mistake?

2022-05-11 07:42 UTC, kraenhansen commented on integration-tests/tests/src/tests/objects.ts
> +    it("collection listener is called on changes to an object's linked object property", async () => {
```suggestion
    it("is called on changes to linked object", async () => {
```

2022-05-11 07:43 UTC, kraenhansen commented on integration-tests/tests/src/tests/objects.ts
> +        realm.create<IDog>("Dog", { age: 4, owner: tmpPerson, name: "rex" });
```suggestion
        const bob = realm.create<IPerson>("Person", { name: "bob", age: 12 });
        realm.create<IDog>("Dog", { age: 4, owner: bob, name: "rex" });
```

2022-05-11 07:43 UTC, kraenhansen commented on integration-tests/tests/src/tests/objects.ts
> +      const collection = realm.objects<IDog>("Dog");
```suggestion
      const dogs = realm.objects<IDog>("Dog");
```

2022-05-11 07:45 UTC, kraenhansen commented on integration-tests/tests/src/utils/perform-action-with-listener.ts
> +  });
I feel this code is a bit too small to justify the added complexity of an abstraction.

2022-05-11 07:45 UTC, kraenhansen commented on vendor/.npmignore
> -*.orig
Looks as if this got deleted by accident.

2022-05-11 07:47 UTC, kraenhansen commented on integration-tests/tests/src/tests/objects.ts
> +  describe("listeners on linked objects", () => {
It seems to me like you're adding listeners on collections and not on individual objects?

```suggestion
  describe("collection listeners", () => {
```

2022-05-11 07:51 UTC, kraenhansen requested changes
I have a few suggestions, most notably I think the `.npmignore` should be restored and the `performActionWithListener` abstraction removed.

2024-01-29 12:23 UTC, takameyer commented
I assume this is mostly covered by now.

2024-01-29 12:23 UTC, closed without merging