Fix https://github.com/realm/realm-js/issues/4513
realm/realm-js pull request #4519
Opened 2022-04-22 10:59 UTC by mfbx9da4

## What, How & Why?
Fixes https://github.com/realm/realm-js/issues/4513#issuecomment-1106241701

2022-04-22 11:05 UTC, mfbx9da4 commented
I didn't spend too long on this so might need some tweaking or cleaning up? @takameyer 

This won't fix https://github.com/realm/realm-js/issues/4518

This also won't fix the fact that:
 
> Using the same object via useObject in two different components will return different references 

(as mentioned in 4513). 

I imagine the code will have changed significantly to solve these latter two issues

2022-04-22 11:11 UTC, takameyer commented
@mfbx9da4 Thanks for the PR!

Slightly different take than my idea:
```tsx
return function useObject<T>(type: string | { new (): T }, primaryKey: PrimaryKey): (T & Realm.Object) | null {
    const realm = useRealm();

    // Create a forceRerender function for the cachedObject to use as its updateCallback, so that
    // the cachedObject can force the component using this hook to re-render when a change occurs.
    const [version, forceRerender] = useReducer((x) => x + 1, 0);

    // Wrap the cachedObject in useMemo, so we only replace it with a new instance if `primaryKey` or `type` change
    const { object, tearDown } = useMemo(
      // TODO: There will be an upcoming breaking change that makes objectForPrimaryKey return null
      // When this is implemented, remove `?? null`
      () =>
        createCachedObject({
          object: realm.objectForPrimaryKey(type, primaryKey) ?? null,
          updateCallback: forceRerender,
        }),
      [type, realm, primaryKey],
    );

    // Invoke the tearDown of the cachedObject when useObject is unmounted
    useEffect(() => {
      return tearDown;
    }, [tearDown]);

    return useMemo(() => {
      // If the object has been deleted or doesn't exist for the given primary key, just return null
      if (object === null || object?.isValid() === false) {
        return null;
      } else {
        // Wrap object in a proxy to update the reference on rerender ( should only rerender when something has changed )
        return new Proxy(object, {});
      }
      // We need version as a dependency in order to trigger a new object reference
    }, [version, object]);
  };
```
We will need to write a test case for this and the other issues in order to avoid regressions.

2022-04-22 11:35 UTC, mfbx9da4 commented
Yeah cool! I like your way of doing it. It would be cleaner IMO if the cached object API was tweaked though

```
function useObject<T>(type: string | { new (): T }, primaryKey: PrimaryKey): (T & Realm.Object) | null {
    const realm = useRealm();

    const cachedObject = useMemo<T & Realm.Object | null>(() => createCachedObject(realm, type, primaryKey), [realm, type, primaryKey]);
    const [version, setVersion] = useState(0)
    

    useEffect(() => {
        return cachedObject?.subscribe(() => setVersion(x => x + 1));
    }, [cachedObject]);

    return useMemo(() => new Proxy(cachedObject.object, {}), [cachedObject, version]);
  };
```

2022-06-15 07:27 UTC, takameyer requested changes
Looks like we need to rebase and write a regression test.  If you got some time to do that, we would be very grateful 🙂 
Otherwise it may be some time before I get to it.

2022-06-15 07:29 UTC, takameyer commented
Adding @tomduncalf and @kraenhansen to the review as well

2022-06-22 14:57 UTC, sdandois commented on packages/realm-react/src/useObject.tsx
> +          const updateCallback = () => {
updateCallback is unused.

2022-06-24 10:31 UTC, takameyer requested changes
The code looks great, but I would like to see a regression test in both `useQueryRender` and `useObjectRender` that verifies that this fix works.  Functionally it should trigger a re-render on the parent component (using `useState`) and verify that the children were not re-rendered.

2022-06-24 10:31 UTC, takameyer commented on packages/realm-react/src/useObject.tsx
> +    return objectRef.current
```suggestion
    // Return the current object reference, which should only cause a rerender when something has changed 
    return objectRef.current
```

2022-06-24 10:31 UTC, takameyer commented on packages/realm-react/src/useQuery.tsx
> +    return collectionRef.current;
```suggestion
    // Return the current collection reference, which should only cause a rerender when something in the visible collection has changed 
    return collectionRef.current;
```

2022-09-30 07:16 UTC, takameyer commented
I've squashed the current changes into a single commit and am continuing this PR on my own here:
https://github.com/realm/realm-js/pull/4958

2022-09-30 07:16 UTC, closed without merging