[@realm/react] add generic type params to hooks
realm/realm-js pull request #4716
Opened 2022-07-10 17:50 UTC by thespacemanatee

## What, How & Why?

This PR is to add generic type params to the hooks in `@realm/react`. Usually, we could type our `Realm.User` by doing the following:

```ts
const app = new Realm.App<RealmFunctionsFactory, UserCustomData>({
  id: REALM_APP_ID,
})
```

but not with `AppProvider` or `UserProvider.`

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

2022-07-10 17:51 UTC, thespacemanatee commented
@cla-bot check

2022-07-11 09:13 UTC, takameyer requested changes
Great catch!  Can you add a snippet to  `packages/realm-react/CHANGELOG.md` for this fix?  We would also appreciate an issue to link to for future reference.

2022-07-12 08:04 UTC, takameyer approved these changes
Looks great.  Thanks for your contribution!

2022-07-12 10:27 UTC, thespacemanatee commented
@takameyer Sorry about that! Not sure why prettier added trailing commas on my setup 😅

2022-07-12 10:40 UTC, takameyer approved these changes

2022-07-12 10:41 UTC, merged