migrate partition-values to TS
realm/realm-js pull request #5359
Opened 2023-02-01 09:21 UTC by JacobOscarGunnarsson

2023-02-07 10:46 UTC, takameyer reviewed
In general, it would be great if we could somehow come up with a way to not have to deploy a new app for every partition value type.  Might be a good refactor later one to reduce the amount of apps being deployed.

2023-02-07 11:07 UTC, takameyer approved these changes
Just some small things.  
Very strange tests.  Will be great to delete them when Flexible Sync reaches 100% adoption.

2023-02-07 11:07 UTC, takameyer commented on integration-tests/tests/src/tests/sync/partition-values.ts
> +        realm1.create("Dog", { _id: new ObjectId(), name: "King" });
the `realm_id` is not set (which is the primary key).  I'm kind of surprised this works at all.
Just did a bit of reading.  I think in general, when the configuration is opened, it just applies a partition to the arbitrary value 42, and any data written there will be partitioned by this, without actually having to explicitly have it's object level field (in this case `realm_id`) to anything at all.
Seems like these tests don't really reflect how most users will use partition based sync, but we are trying to migrate everyone away from that anyway.
Nothing to do here, just was confused what was happening here.

2023-02-07 11:07 UTC, takameyer commented on integration-tests/realm-apps/pv-int-tests/config.json
> +        "development_mode_enabled": false
In any case, after reading the tests, we can probably just leave this alone.

2023-02-09 19:22 UTC, kraenhansen requested changes
Since this PR isn't making changes to any `package.json` files, I'd say the changes to the `package-lock.json` file should be left out. Feel free to open a separate PR with the changes if those changes are actually needed.

2023-02-10 13:32 UTC, kraenhansen approved these changes

2023-02-13 15:22 UTC, merged