Documenting our three tiers
realm/realm-js pull request #5396
Opened 2023-02-09 10:36 UTC by kneth

It is not realistic that we can support all combinations of packages, versions, and platforms. We should be transparent about our priorities.

2023-02-09 15:09 UTC, kneth commented on README.md
> +It is exciting to have users, and we want to support you as good as possible. We cannot provide all the support we want, and let's be transparent about. Our community support (Github issues in this a
Good catch. "about our priorities" might be what I was thinking :-)

2023-02-09 20:49 UTC, geragray requested changes

2023-02-09 20:49 UTC, geragray commented on README.md
>  Please see the detailed instructions in our docs to use [Realm JavaScript for Node.js](https://docs.mongodb.com/realm/sdk/node/) and [Realm JavaScript for React Native](https://docs.mongodb.com/realm
Docs URL has changed. New ones are https://www.mongodb.com/docs/realm/sdk/node/ and https://www.mongodb.com/docs/realm/sdk/react-native/. I added https://github.com/realm/realm-js/pull/5405

2023-02-09 20:49 UTC, geragray commented on README.md
> +It is exciting to have users, and we want to support you as good as possible. We cannot provide all the support we want, and let's be transparent about. Our community support (Github issues in this a
I propose to remove the sentence completely, we simply can focus that we do provide support and explain tiers https://github.com/realm/realm-js/pull/5405

2023-02-13 21:27 UTC, geragray approved these changes

2023-02-13 21:29 UTC, merged