Fixed some types definition in bindgen
realm/realm-js pull request #5524
Opened 2023-03-02 14:20 UTC by papafe

Fixed some types definition on bindgen branch so that methods won't give type errors when being used with RealmObject with or without specifying the concrete type, similar to what has been done in https://github.com/realm/realm-js/pull/5487 with Object.linkingObjects

(had to close the previous PR because I had some issues with rebasing, sorry for that)

2023-03-03 07:06 UTC, takameyer requested changes
I just tested this out and it looks as if this fixes using a class with `realm.create`.  Could we write a test for this to avoid a future regression?

2023-03-03 10:59 UTC, kraenhansen commented on packages/realm/src/Realm.ts
> +  create<T extends AnyRealmObject = RealmObject & DefaultObject>(
Is the default really needed here? I imagine it'll be better to leave it out and rely on type inference from the first argument.

2023-03-03 10:59 UTC, kraenhansen commented on packages/realm/src/Realm.ts
> +  objectForPrimaryKey<T extends AnyRealmObject = RealmObject & DefaultObject>(
Same as my comment above on the default value here.

2023-03-13 09:54 UTC, papafe commented
> I just tested this out and it looks as if this fixes using a class with `realm.create`. Could we write a test for this to avoid a future regression?
@takameyer I've discussed about this with @kraenhansen, and probably the best approach here would be to enable the tests to fail when there are type errors, but we can't do it now without fixing all the pre-existing errors too. 
I've modified the class definition for `Person` and `Dog`, this will definitely give a type error in `create` and the other methods if we have a regression, so that will be covered when at some point type errors will be considered as test fails.

2023-03-15 10:29 UTC, merged