Support full-text index decorator in babel plugin
realm/realm-js pull request #6218
Opened 2023-10-27 18:17 UTC by atdyer

This closes #5800 by adding support for the `index("full-text")` decorator.

- Check for `index` decorator calls that are passed the string "full-text" and subsequently add the `{ indexed: "full-text" }` property to the schema.
- Update README with description and example of indexing a string field by full text
- Update tests to verify schemas with full-text indexing are properly generated

2023-10-31 12:52 UTC, kneth approved these changes

2023-10-31 12:56 UTC, kneth commented
@atdyer Thank you for your contribution. It looks good to me, and I have requested the team to review your PR.

I like that you have taken the time to update `README.md` and added tests.

Some test suites will fail since you don't have permission to launch some component - don't worry about that.

Once merged, we will update `CHANGELOG.md` and do a release of the babel plugin.

2023-10-31 14:06 UTC, takameyer requested changes
I would approve this after the comments from @kraenhansen are resolved.

2023-10-31 14:06 UTC, takameyer commented on packages/babel-plugin/src/index.test.ts
> +    })
I agree that an error should be thrown in this case.

2023-10-31 14:06 UTC, takameyer commented on packages/babel-plugin/src/plugin/index.ts
> +      && indexDecoratorCall.callExpression.arguments[0].value === 'full-text'
It should just forward whatever is given to the schema.  Then at least we get a run-time error.
Unfortunately it's not possible to get type errors here, which would be great.

2023-11-02 12:48 UTC, elle-j reviewed
Thanks for taking the time to understand this issue and propose a solution! 🚀

2023-11-02 12:48 UTC, elle-j commented on packages/babel-plugin/src/index.test.ts
> +    })
Helping the user understand what's wrong and how to correct it also aligns better with the goals of the updated schema parser 👍

2023-11-06 20:38 UTC, atdyer commented
@takameyer I believe I've addressed all your comments - now any string passed into the `@index` decorator as a parameter will be passed through to the final schema. If there's anything I've missed please let me know an I'll fix it up!

2023-11-11 20:11 UTC, kraenhansen approved these changes
As far as I can tell, this just needs an entry in the [changelog](https://github.com/realm/realm-js/blob/main/packages/babel-plugin/CHANGELOG.md).

2023-11-13 14:13 UTC, takameyer approved these changes
Looks good to me 👍🏼

2023-11-13 14:22 UTC, elle-j approved these changes
Nice update!

2023-11-20 14:36 UTC, merged